# This is a basic workflow to help you get started with Actions

name: running acceptance test
# Controls when the workflow will run
#    branches: [ main LTS ]
on:
  # Triggers the workflow on push or pull request events but only for the 3.4.0 branch
  push:
    paths-ignore:
      - 'docs/**'
#      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      message:
        description: 'running acceptance test'     
        required: true

env:
  commitmsg: ${{ github.event.head_commit.message }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"


  acceptancetest_102:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: test one of the test test_loop_improved_reweighting
        run: |
            cd $GITHUB_WORKSPACE
            cp input/.mg5_configuration_default.txt input/mg5_configuration.txt
            sudo pip install numpy
            which f2py
            echo "f2py_compiler = $(which f2py)" >> input/mg5_configuration.txt
            cp Template/LO/Source/.make_opts Template/LO/Source/make_opts
            echo "install lhapdf6" > cmd
            #echo "install pythia8" >> cmd
            ./bin/mg5_aMC cmd
            cat HEPTools/lhapdf6_py3/lhapdf6_install.log
            ls HEPTools/lhapdf6_py3/bin
            ls HEPTools/lhapdf6_py3/lib 
            echo "lhapdf-config = /home/runner/work/mg5amcnlo/mg5amcnlo/HEPTools/lhapdf6_py3/bin/lhapdf-config" >> input/mg5_configuration.txt
            export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/runner/work/mg5amcnlo/mg5amcnlo/HEPTools/lhapdf6_py3//lib:/home/runner/work/mg5amcnlo/mg5amcnlo/HEPTools/lib
            ./tests/test_manager.py  test_nlo_reweighting -pA -t0 -l INFO
